-- Delete existing chronic-illness questions
DELETE FROM questions WHERE template_id = 'chronic-illness';

-- Insert chronic-illness questions
INSERT INTO questions (id, question, category, template_id, question_number) VALUES

-- FOUNDATION QUESTIONS (1-15)
('chronic-illness-1', 'Write about the first time you noticed something was wrong with your health. What were you doing? What made you realize this wasn''t normal? How long did it take you to seek help?', 'reflection', 'chronic-illness', 1),
('chronic-illness-2', 'Document 3 specific moments in the past 6 months when your symptoms significantly impacted your day. What were you trying to do? What did you have to give up or modify? How did that make you feel?', 'reflection', 'chronic-illness', 2),
('chronic-illness-3', 'Reflect on how you described your illness to yourself 6 months ago versus now. What words have changed? What does this shift tell you about your journey?', 'reflection', 'chronic-illness', 3),
('chronic-illness-4', 'List the activities you used to do effortlessly that now require planning or energy. For each one, note: Do you miss it? Have you found alternatives? Or have you let it go?', 'reflection', 'chronic-illness', 4),
('chronic-illness-5', 'Write about a time when someone said "but you don''t look sick." What was happening? How did you respond? What do you wish you had said?', 'reflection', 'chronic-illness', 5),
('chronic-illness-6', 'Think about your best day and worst day in the past month. What made them different? What patterns do you notice about what helps versus what hurts?', 'reflection', 'chronic-illness', 6),
('chronic-illness-7', 'Document the times of day when you typically feel your best and worst. What''s your energy pattern? How does this compare to your pre-illness rhythm?', 'reflection', 'chronic-illness', 7),
('chronic-illness-8', 'Reflect on who you were before this diagnosis. What parts of that person do you still have? What have you had to grieve? What new strengths have you discovered?', 'reflection', 'chronic-illness', 8),
('chronic-illness-9', 'Write about 3 relationships that changed after your diagnosis - for better or worse. What specifically shifted? What does this tell you about what you need from people now?', 'reflection', 'chronic-illness', 9),
('chronic-illness-10', 'List the assumptions you had about chronic illness before you had one. Which ones were wrong? What do you know now that you wish you could tell your past self?', 'reflection', 'chronic-illness', 10),
('chronic-illness-11', 'Document the last time you pushed through symptoms and paid for it later. What were you trying to prove or accomplish? What did this cost you? What would you do differently now?', 'reflection', 'chronic-illness', 11),
('chronic-illness-12', 'Reflect on how you talk about your illness to different people - family, friends, coworkers, strangers. What do these different versions reveal about what you''re protecting or trying to control?', 'reflection', 'chronic-illness', 12),
('chronic-illness-13', 'Write about a moment when you felt truly understood in your experience. Who was it? What did they say or do? Why did it resonate so deeply?', 'reflection', 'chronic-illness', 13),
('chronic-illness-14', 'Think about the identity shift from "temporarily sick" to "chronically ill." When did that mental transition happen for you? What triggered it? How are you making peace with it?', 'reflection', 'chronic-illness', 14),
('chronic-illness-15', 'Document what "a good life" meant to you before versus what it means now. What had to change in that definition? What feels like loss? What feels like growth?', 'reflection', 'chronic-illness', 15),

-- RESEARCH QUESTIONS (16-28)
('chronic-illness-16', 'Research your specific condition and list 3 treatment approaches your current doctor hasn''t mentioned. For each, note: Is there evidence? What would it require? Is it worth exploring?', 'research', 'chronic-illness', 16),
('chronic-illness-17', 'Document every medication and supplement you take. For each, note: What''s it supposed to do? What side effects have you noticed? When did you last evaluate if it''s actually helping?', 'research', 'chronic-illness', 17),
('chronic-illness-18', 'Create a symptom tracker for one week. For each significant symptom, note: time, severity (1-10), what you were doing before, what helped (if anything). What patterns emerge?', 'research', 'chronic-illness', 18),
('chronic-illness-19', 'List all your current healthcare providers. For each, note: How did you find them? Do they listen to you? Do they coordinate with your other providers? Would you recommend them to someone else with your condition?', 'research', 'chronic-illness', 19),
('chronic-illness-20', 'Research patient communities for your condition (online forums, Facebook groups, local support groups). Join 2 and observe for a week. What are people talking about? What questions come up repeatedly? What advice seems helpful versus harmful?', 'research', 'chronic-illness', 20),
('chronic-illness-21', 'Document your insurance coverage in plain language. What does your plan actually cover for your condition? What are your out-of-pocket maximums? What hoops do you have to jump through for specialist visits or treatments?', 'research', 'chronic-illness', 21),
('chronic-illness-22', 'List the last 5 medical appointments you had. For each: What was accomplished? What was a waste of time? What question did you forget to ask? What would make the next one more productive?', 'research', 'chronic-illness', 22),
('chronic-illness-23', 'Research workplace accommodations for your specific condition. List 5 that could help you. For each: Is it reasonable? How would you request it? What documentation would you need?', 'research', 'chronic-illness', 23),
('chronic-illness-24', 'Create an inventory of your current energy management strategies. For each: Where did you learn it? Does it actually work for you? What''s the evidence versus what''s just hopeful thinking?', 'research', 'chronic-illness', 24),
('chronic-illness-25', 'Document every specialist you''ve seen for this condition. For each: What did they tell you? Did their advice conflict with others? Who did you trust and why?', 'research', 'chronic-illness', 25),
('chronic-illness-26', 'Research the typical progression of your condition. What does the medical literature say about 5-year, 10-year outlook? How does this compare to what your doctor has told you? What questions does this raise?', 'research', 'chronic-illness', 26),
('chronic-illness-27', 'List all the diagnostic tests you''ve had in the past year. For each: What were they looking for? What did they find (or not find)? What did you learn? What questions remain unanswered?', 'research', 'chronic-illness', 27),
('chronic-illness-28', 'Research emergency protocols for your condition. What symptoms require immediate medical attention? What should you do first? Who should you call? What information do paramedics need to know about your condition?', 'research', 'chronic-illness', 28),

-- PLANNING QUESTIONS (29-45)
('chronic-illness-29', 'Map out your ideal week given your current energy levels. What activities are non-negotiable? What can flex? What needs to be eliminated? How far is this from your actual week?', 'planning', 'chronic-illness', 29),
('chronic-illness-30', 'Plan how you''ll handle your next flare-up differently than the last one. What early warning signs will you watch for? What will you do in the first 24 hours? What help will you line up in advance?', 'planning', 'chronic-illness', 30),
('chronic-illness-31', 'Design your "minimum viable day" - the baseline that counts as success when you''re struggling. What does it include? What doesn''t make the cut? How will you remind yourself that this is enough?', 'planning', 'chronic-illness', 31),
('chronic-illness-32', 'Create a decision framework for when to push through versus when to rest. What factors matter? What are your red lines? What has experience taught you about the cost of getting this wrong?', 'planning', 'chronic-illness', 32),
('chronic-illness-33', 'Plan how you''ll talk about your illness at work over the next 6 months. Who needs to know what? What accommodations will you request? What''s your script for different scenarios?', 'planning', 'chronic-illness', 33),
('chronic-illness-34', 'Map your support network. Who can you call for medical emergencies? Who''s good for practical help? Who provides emotional support? Where are the gaps? How will you fill them?', 'planning', 'chronic-illness', 34),
('chronic-illness-35', 'Design your medication and appointment management system. How will you track what you take? How will you remember appointments? How will you organize medical records? What''s sustainable for you?', 'planning', 'chronic-illness', 35),
('chronic-illness-36', 'Plan your financial strategy for the next year. What are your expected medical costs? What can you do to reduce them? What savings do you need for emergencies? What trade-offs are you willing to make?', 'planning', 'chronic-illness', 36),
('chronic-illness-37', 'Create boundaries around your illness. When will you talk about it versus when will you not? What questions will you answer versus deflect? How will you protect your energy from other people''s curiosity or advice?', 'planning', 'chronic-illness', 37),
('chronic-illness-38', 'Plan how you''ll maintain relationships that matter despite your limitations. What can you realistically commit to? What needs to change? How will you communicate these changes honestly?', 'planning', 'chronic-illness', 38),
('chronic-illness-39', 'Design your self-advocacy strategy for medical appointments. How will you prepare? What documentation will you bring? How will you push back when dismissed? What''s your plan if a provider isn''t listening?', 'planning', 'chronic-illness', 39),
('chronic-illness-40', 'Map out how your condition affects your career trajectory over the next 3 years. What''s realistic to pursue? What might you need to let go of? What alternative paths could work better?', 'planning', 'chronic-illness', 40),
('chronic-illness-41', 'Create a plan for protecting your mental health alongside your physical health. What are your early warning signs of depression or burnout? What interventions work for you? Who will you tell if you''re struggling?', 'planning', 'chronic-illness', 41),
('chronic-illness-42', 'Plan how you''ll handle "good days" without sabotaging yourself. What''s worth doing with extra energy? What''s a trap that will cost you tomorrow? How will you find the balance?', 'planning', 'chronic-illness', 42),
('chronic-illness-43', 'Design your rest and recovery protocol. What actually restores your energy? What just fills time? How much rest do you actually need? How will you give yourself permission to take it?', 'planning', 'chronic-illness', 43),
('chronic-illness-44', 'Map out the conversations you need to have with family members about your illness. Who needs to understand what? What support do you need from them? What''s not their business? How will you communicate your needs clearly?', 'planning', 'chronic-illness', 44),
('chronic-illness-45', 'Plan your approach to trying new treatments or interventions. What criteria will you use to evaluate them? How long will you give something before deciding? How will you avoid the desperation trap of trying everything?', 'planning', 'chronic-illness', 45),

-- ACTION QUESTIONS (46-60)
('chronic-illness-46', 'Write down 3 questions you''ll ask at your next doctor''s appointment. Make them specific. Practice saying them out loud. What information do you need to make decisions?', 'action', 'chronic-illness', 46),
('chronic-illness-47', 'Schedule one task this week to improve your health management - organizing medical records, researching a new provider, setting up a medication system. What will you do? When exactly will you do it?', 'action', 'chronic-illness', 47),
('chronic-illness-48', 'Document your current treatment plan in writing. What are you taking? Why? What''s the expected outcome? What side effects are you monitoring? When will you re-evaluate?', 'action', 'chronic-illness', 48),
('chronic-illness-49', 'Identify one relationship where you need to set a boundary about your illness. What will you say? When will you have this conversation? What outcome do you want?', 'action', 'chronic-illness', 49),
('chronic-illness-50', 'Create a one-page medical summary to carry with you. What are your key diagnoses? Current medications? Allergies? Emergency contacts? Where will you keep it?', 'action', 'chronic-illness', 50),
('chronic-illness-51', 'Choose one energy-draining obligation to eliminate or modify this month. What is it? How will you communicate this change? What will you do with the freed-up energy?', 'action', 'chronic-illness', 51),
('chronic-illness-52', 'Write an email to your manager requesting one specific accommodation. What do you need? Why will it help? What documentation can you provide? When will you send it?', 'action', 'chronic-illness', 52),
('chronic-illness-53', 'Identify one doctor or specialist who isn''t serving you well. What makes them inadequate? What will you do about it? When will you start looking for a replacement?', 'action', 'chronic-illness', 53),
('chronic-illness-54', 'Document three concrete ways someone can help you this week. Be specific - not "support me" but actual tasks. Who will you ask? How will you ask?', 'action', 'chronic-illness', 54),
('chronic-illness-55', 'Create a crisis plan for your next bad day or flare-up. What will you do first? Who will you notify? What can you postpone? What help do you have lined up? Where will you keep this plan?', 'action', 'chronic-illness', 55),
('chronic-illness-56', 'Schedule a mental health check-in - with a therapist, counselor, or trusted friend. When will it be? What do you need to talk through? What support are you seeking?', 'action', 'chronic-illness', 56),
('chronic-illness-57', 'Join one patient community for your condition this week. Introduce yourself. Ask one question you''ve been struggling with. What do you hope to learn?', 'action', 'chronic-illness', 57),
('chronic-illness-58', 'Review your calendar for the next month. Identify 3 commitments that aren''t worth your limited energy. How will you reduce, delegate, or cancel them? When will you take action?', 'action', 'chronic-illness', 58),
('chronic-illness-59', 'Start tracking one specific symptom or pattern for the next two weeks. What will you track? How will you record it? What are you trying to learn? When will you review the data?', 'action', 'chronic-illness', 59),
('chronic-illness-60', 'Write a letter to yourself about what you''ve learned about living with chronic illness. What wisdom would you share with someone newly diagnosed? What do you want to remember on hard days? Keep it somewhere you can find it when you need it.', 'action', 'chronic-illness', 60);
