-- Delete existing questions for planning-funeral guide
DELETE FROM questions WHERE template_id = 'planning-funeral';

-- Insert 55 comprehensive questions for planning-funeral guide

-- Foundation Questions (1-14) - 25.5%
INSERT INTO questions (id, question, category, template_id, question_number) VALUES
('planning-funeral-1', 'Write about your earliest memory involving death or funerals. What was the experience like? What stood out to you about how people handled it - what felt comforting, what felt strange, what stayed with you?', 'reflection', 'planning-funeral', 1),
('planning-funeral-2', 'Reflect on 3 funerals or memorial services you''ve attended. For each, note what made it meaningful or meaningful-less. What moments actually helped people grieve? What parts felt performative or empty?', 'reflection', 'planning-funeral', 2),
('planning-funeral-3', 'Think about how the person you''re planning for talked about death in the past year. Write down any comments they made - jokes, serious statements, things they said about other people''s funerals. What values or preferences were hidden in those comments?', 'reflection', 'planning-funeral', 3),
('planning-funeral-4', 'Document the moment you realized you needed to plan this funeral. Where were you? What triggered the realization? How did your body feel? Write about the specific thoughts that went through your mind.', 'reflection', 'planning-funeral', 4),
('planning-funeral-5', 'Reflect on your relationship with the person. Write about 3 specific moments that capture who they were to you - not their accomplishments, but small, ordinary moments that showed their essence. What would be lost if these moments weren''t honored?', 'reflection', 'planning-funeral', 5),
('planning-funeral-6', 'Think about the phrase "a good funeral" or "a good death." What does that mean to you, specifically? What would make you feel like you honored this person well? What would haunt you later if you missed it?', 'reflection', 'planning-funeral', 6),
('planning-funeral-7', 'List the family or cultural expectations you''re aware of for this funeral. For each expectation, note: who holds it, how strongly, and whether it aligns with what you believe the deceased would have wanted. Where do you feel tension?', 'reflection', 'planning-funeral', 7),
('planning-funeral-8', 'Write about your own relationship with grief and emotion in public. When have you felt comfortable crying in front of others? When have you needed to be "strong"? How might this affect the decisions you make about the service?', 'reflection', 'planning-funeral', 8),
('planning-funeral-9', 'Reflect on the past week since you started thinking about this funeral. What decisions have you been avoiding? What thoughts wake you up at night? What feels too overwhelming to face right now?', 'reflection', 'planning-funeral', 9),
('planning-funeral-10', 'Think about how this person would want to be remembered. Not the sanitized, formal version - but the real them. Write about 3 qualities or quirks that were authentically them, even if they weren''t always flattering. Should these be part of the service?', 'reflection', 'planning-funeral', 10),
('planning-funeral-11', 'Document the last meaningful conversation you had with this person. What did you talk about? What didn''t you get to say? How might this "unfinished business" influence what you want the funeral to accomplish?', 'reflection', 'planning-funeral', 11),
('planning-funeral-12', 'Reflect on who you are in your family system. Are you the organizer, the peacemaker, the emotional one, the practical one? Write about how this role might affect your funeral planning and what support you might need to step out of that pattern if needed.', 'reflection', 'planning-funeral', 12),
('planning-funeral-13', 'Think about the communities this person belonged to - work, hobbies, neighborhood, online groups, old friendships. For each, write down a specific way they showed up in that community. Which of these communities need to be part of the funeral, and which might need separate recognition?', 'reflection', 'planning-funeral', 13),
('planning-funeral-14', 'Write about your biggest fear regarding this funeral. Not abstract fears - the specific, concrete thing you''re afraid will happen. What does this fear tell you about what really matters to you in this process?', 'reflection', 'planning-funeral', 14);

-- Research Questions (15-26) - 21.8%
INSERT INTO questions (id, question, category, template_id, question_number) VALUES
('planning-funeral-15', 'Research 3 funeral homes in your area. For each, document: pricing for basic services (get the general price list), reviews from families, whether they felt corporate or personal, and your gut reaction to their website/presence. What style feels right for this person?', 'research', 'planning-funeral', 15),
('planning-funeral-16', 'Investigate the legal requirements in your state/region. Document: how quickly must the body be buried/cremated, what paperwork is required, who can legally make decisions, and what permits are needed. Write down what surprised you or what creates time pressure.', 'research', 'planning-funeral', 16),
('planning-funeral-17', 'Research the costs of burial versus cremation in your area. Document specific numbers: burial (casket, plot, opening/closing grave, headstone), cremation (basic cremation, urn, columbarium or scattering). Include what''s NOT included in the base price that you''d need to add.', 'research', 'planning-funeral', 17),
('planning-funeral-18', 'Look into any pre-planning documents the person may have created. Check for: written wishes, pre-paid funeral plans, will/estate documents, advance directives, conversations with other family members. Document what you found and what''s still unknown.', 'research', 'planning-funeral', 18),
('planning-funeral-19', 'Research the religious or cultural traditions relevant to this funeral. Document specific practices: timing of burial, preparation of the body, who can attend, dress code, role of clergy, traditional prayers or readings. Note which traditions are required vs. optional vs. adaptable.', 'research', 'planning-funeral', 19),
('planning-funeral-20', 'Investigate the financial resources available. Check: life insurance policies (amount, beneficiary, how to claim), bank accounts, veteran benefits if applicable, Social Security death benefit, employer benefits. Write down confirmed amounts vs. what you''re still tracking down.', 'research', 'planning-funeral', 20),
('planning-funeral-21', 'Research alternative funeral options beyond traditional burial/cremation. Look into: green burial, home funeral, body donation to science, aquamation, conservation burial. For each option, note: cost, legal status in your area, and whether it aligns with the person''s values.', 'research', 'planning-funeral', 21),
('planning-funeral-22', 'Look into venue options for the service. Research 3 possible locations: funeral home chapel, religious building, community space, outdoor location, or family home. For each, document: capacity, cost, restrictions, availability, and what atmosphere it would create.', 'research', 'planning-funeral', 22),
('planning-funeral-23', 'Research what happens to the person''s online presence. Investigate policies for: social media accounts, email, photos stored in cloud, websites they maintained, online communities they participated in. Document how to memorialize or close each account.', 'research', 'planning-funeral', 23),
('planning-funeral-24', 'Investigate options for memorialization beyond the funeral itself. Research: online memorial pages, charity donations in their name, memorial scholarships, planted trees, benches, ongoing community contributions. Note costs and coordination required for each.', 'research', 'planning-funeral', 24),
('planning-funeral-25', 'Look up the person''s military service records if applicable. Research: eligibility for military honors, burial in national cemetery, flag presentation, veteran benefits available. Document what forms are needed and who to contact.', 'research', 'planning-funeral', 25),
('planning-funeral-26', 'Research grief support resources for yourself and family. Find: local grief counselors, support groups, online communities, books or resources specific to your type of loss. Document 3 specific resources with contact info that you could access in the weeks after the funeral.', 'research', 'planning-funeral', 26);

-- Planning Questions (27-42) - 29.1%
INSERT INTO questions (id, question, category, template_id, question_number) VALUES
('planning-funeral-27', 'Based on your research, write down your funeral budget in three tiers: bare minimum (what must happen), realistic (what you can afford), and ideal (if money weren''t the main constraint). For each tier, specify the total cost and what it includes.', 'planning', 'planning-funeral', 27),
('planning-funeral-28', 'Design the structure of the service. Map out the flow: gathering/visitation, formal service, committal/burial, reception. For each part, note: how long, who leads it, what tone you want, and which parts are negotiable if you run out of time or energy.', 'planning', 'planning-funeral', 28),
('planning-funeral-29', 'Plan who will have active roles in the service. List specific people for: eulogy, readings, music, pallbearers, greeters, photo display curator. For each person, write why they''re the right choice and have you actually asked them yet?', 'planning', 'planning-funeral', 29),
('planning-funeral-30', 'Create the notification strategy. Plan: who needs to be told immediately (inner circle), who needs to be informed soon (extended network), and who will learn via obituary/social media. For each group, write who will contact them and what method you''ll use.', 'planning', 'planning-funeral', 30),
('planning-funeral-31', 'Draft the core message about this person''s life. Write 3-5 sentences capturing their essence - not achievements, but who they were, what they cared about, how they affected others. This will guide the obituary, eulogy, and how you talk about them.', 'planning', 'planning-funeral', 31),
('planning-funeral-32', 'Plan the sensory experience of the funeral. Consider: what music (specific songs, live or recorded), what visuals (photos, videos, flowers, symbols), what physical objects (guest book, memory table, handouts). For each, write what feeling or memory you want it to evoke.', 'planning', 'planning-funeral', 32),
('planning-funeral-33', 'Anticipate family conflicts or difficult dynamics. Write down: who might clash with whom, what past tensions could resurface, what decisions might cause disagreement, who might feel left out. For each potential conflict, plan: how you''ll prevent it or how you''ll handle it if it happens.', 'planning', 'planning-funeral', 33),
('planning-funeral-34', 'Design how you''ll handle your own grief during the service. Plan: who will be your support person, what will you do if you become overwhelmed, what tasks can you delegate, when will you give yourself permission to just be present. Write down your escape plan if you need to step away.', 'planning', 'planning-funeral', 34),
('planning-funeral-35', 'Plan the timeline from death to service. Map out: when will viewing/visitation happen, how many days until the service, when is burial/cremation, when is reception. For each decision, note: what''s driving this timeline (religion, family travel, your capacity, venue availability)?', 'planning', 'planning-funeral', 35),
('planning-funeral-36', 'Create the guest experience plan. Consider: how will out-of-town guests find lodging, what happens with young children during the service, how will elderly/disabled guests access the venue, what will people do between service and reception. Write down specific accommodations you''ll arrange.', 'planning', 'planning-funeral', 36),
('planning-funeral-37', 'Plan how to honor the person''s wishes while managing family expectations. If there''s a conflict between what the deceased wanted and what family expects, write out: what the conflict is, who will be upset by each choice, and what compromise (if any) honors both the person and the family.', 'planning', 'planning-funeral', 37),
('planning-funeral-38', 'Design the participation opportunities for attendees. Plan: will there be open mic sharing, a memory book, photo contributions, charitable donations in lieu of flowers, a specific action people can take? For each option, note what you''re asking people to do and how you''ll facilitate it.', 'planning', 'planning-funeral', 38),
('planning-funeral-39', 'Plan the obituary strategy. Decide: will you publish in newspapers (which ones, what cost), post online (which sites), share on social media (which platforms, who posts). Draft the key facts now: dates, survivors, service info, donation preferences. Who will write the full version?', 'planning', 'planning-funeral', 39),
('planning-funeral-40', 'Create your decision-making framework. Write down: what decisions you can make alone, what requires input from specific family members, what you''ll delegate entirely, and what you simply won''t compromise on. This is your boundary document.', 'planning', 'planning-funeral', 40),
('planning-funeral-41', 'Plan the reception or gathering after the service. Decide: location (home, restaurant, venue), format (sit-down meal, casual reception, nothing formal), who will coordinate food, how long it will last. Write down what purpose this gathering serves - celebration, support, closure, or something else?', 'planning', 'planning-funeral', 41),
('planning-funeral-42', 'Design your own support structure for the week of the funeral. Plan: who will stay with you, who will handle practical tasks (feeding you, managing calls, driving), what you''ll say when you need space, how you''ll ask for help. Write down 3 people and their specific roles.', 'planning', 'planning-funeral', 42);

-- Action Questions (43-55) - 23.6%
INSERT INTO questions (id, question, category, template_id, question_number) VALUES
('planning-funeral-43', 'Choose and contact a funeral home or burial coordinator. Write down: which funeral home you''ll call (specific name and phone), what questions you''ll ask, what information you need to gather before the call. Schedule when you''ll make this call (specific date and time).', 'action', 'planning-funeral', 43),
('planning-funeral-44', 'Gather essential documents today. Create a physical folder with: death certificate (order copies), will, insurance policies, military discharge papers, marriage certificate, Social Security card. Write down what you have, what you''re missing, and where to get it.', 'action', 'planning-funeral', 44),
('planning-funeral-45', 'Start the obituary draft right now. Write the basic framework: full name, dates, immediate family, service information, donation preferences. It doesn''t need to be beautiful yet - just get the facts down. Who will review it before it''s published?', 'action', 'planning-funeral', 45),
('planning-funeral-46', 'Create the master task list and delegate. Write down every single task that needs to happen, then assign each task to a specific person with a specific deadline. Put one person in charge of tracking this list. When will you have your first coordination meeting?', 'action', 'planning-funeral', 46),
('planning-funeral-47', 'Collect photos and memorabilia this week. Ask specific people: "Send me 3 photos of [person] that capture them at their best." Set a deadline. Create a shared folder (Google Drive, Dropbox) where people can upload. Who will curate these into a display?', 'action', 'planning-funeral', 47),
('planning-funeral-48', 'Reach out to the people you want in active roles. For each person (eulogy, readings, music, pallbearer), send them a specific message today: what you''re asking, why you chose them, that it''s okay to say no. Don''t wait - who will you contact first?', 'action', 'planning-funeral', 48),
('planning-funeral-49', 'Set up the coordination system. Choose: shared document for tracking tasks (Google Doc, spreadsheet), group chat for family coordination (specific platform), and one point person for vendor communications. Create these systems today and share access with key people.', 'action', 'planning-funeral', 49),
('planning-funeral-50', 'Notify the inner circle immediately. Make a list of the 5-10 people who need to hear directly from you before they see it anywhere else. Call or text each of them today. Write down: who you told, how they responded, what support they offered.', 'action', 'planning-funeral', 50),
('planning-funeral-51', 'Make the burial versus cremation decision by [specific date]. Based on everything you know - the person''s wishes, religious requirements, family input, budget, your own feelings - write down your decision and who needs to be informed. Schedule the conversation if needed.', 'action', 'planning-funeral', 51),
('planning-funeral-52', 'Book the venue and set the date. Call your chosen location today, check availability for your preferred dates, and make the reservation. Write down: venue name, date, time, deposit required, cancellation policy. Send this information to family immediately after booking.', 'action', 'planning-funeral', 52),
('planning-funeral-53', 'Create the one-page service outline. Write down the actual running order: what happens minute-by-minute, who does what, what music plays when, where people sit. Make this concrete enough that someone else could run the service if you''re too overwhelmed. Share it with your officiant or coordinator.', 'action', 'planning-funeral', 53),
('planning-funeral-54', 'Schedule your own support for the week after the funeral. Right now, put 3 specific things in your calendar: grief counseling appointment, coffee with a trusted friend, one day where someone else handles logistics. Write down the dates and confirm with the people involved.', 'action', 'planning-funeral', 54),
('planning-funeral-55', 'Set the review checkpoint. Write down a date exactly 3 days before the funeral. On that date, you''ll review everything: what''s confirmed, what''s still pending, what''s falling through the cracks, who needs to be followed up with. Put this in your calendar now with a link to all your planning documents.', 'action', 'planning-funeral', 55);
